kill(all)$

r : 2$
T : 6$
n : r*T$

m : zeromatrix(n,n)$

( for i:1 step r thru n do (
      m[i][i] : a[i][i]
  )
)$

( for i:1 step r thru n-r do (
      m[i][i+r] : a[i][i+r]
  )
)$

( for i:1 step r thru n-r do (
      m[i+r][i] : a[i][i+r]
  )
)$

( for i:1 step r thru n-2*r do (
      m[i][i+2*r] : a[i][i+2*r]
  )
)$

( for i:1 step r thru n-2*r do (
      m[i+2*r][i] : a[i][i+2*r]
  )
)$

m;